### PR TITLE
Update instructions.md

### PR DESCRIPTION
**Pull request by hcorona-zz**
fixes #24

### CODE REVIEW

**Comment by hcorona-zz** [comment]
👍

**Comment by hcorona-zz** [comment]
this is OK

**Review by kevllino — APPROVED** [review]
Awesome @hcorona !

**Comment by kevllino** [comment]
👍

**Comment by hcorona-zz** [comment]
@kevllino this actually needs you to go to the "review changes" on top-right side of the page : https://github.com/hcorona/recsys-101-workshop/pull/24/files , its the GitHub version of Zappr I guess

**Review by kevllino — APPROVED** [review]

**Review by kevllino — APPROVED** [review]
👍

**Pull request merged**
